version: '3.8'
services:
  api:
    build: ./MyWebApi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TURSO_URL=http://libsql:8080
      - TURSO_AUTH_TOKEN=local-dev-token
    depends_on:
      - libsql

  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    volumes:
      - libsql_data:/var/lib/sqld

volumes:
  libsql_data:
